version: '3'

services:
  local-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123123"
    volumes:
      - ./01-basegeografica.sql:/docker-entrypoint-initdb.d/01-basegeografica.sql
      - ./02-basegeografica.sql:/docker-entrypoint-initdb.d/02-basegeografica.sql
    ports:
      - "5432:5432"